name: Continuous Integration

on:
  push:
    branches: [main]
    paths: ["**.zig"]

  pull_request:
    branches: [main]
    paths: ["**.zig"]

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Run Loog server log analyzer
        run: |
          zig env
          zig build exe

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Run lints
        run: zig build lint
